{% set name = "dsps" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d09fc3439871eb8df61456a13e250a5ad2d236776cb536411576289d694f2098

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - jax
    - h5py
    - diffmah
    - diffstar >=0.1.0

test:
  imports:
    - dsps

about:
  home: https://github.com/ArgonneCPAC/dsps
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Differentiable Stellar Population Synthesis

extra:
  recipe-maintainers:
    - beckermr
