{% set name = "dsps" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bfa1cd193bb03730e6401770f9a504c1482d9d6038e697c5172f9928a480f4f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - jax
    - h5py
{% if version == "0.3.1" %}
    - scipy
{% endif %}
    - diffmah
    - diffstar >=0.1.0

test:
  imports:
    - dsps

about:
  home: https://github.com/ArgonneCPAC/dsps
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Differentiable Stellar Population Synthesis

extra:
  recipe-maintainers:
    - beckermr
