{% set name = "dsps" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2862094bca324defb33b8f0104f5d64a87737ccc27ab6a179fdf6481189e0063

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - jax
    - h5py
{% if version == "0.3.1" %}
    - scipy
{% endif %}
    - diffmah
    - diffstar >=0.1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - dsps

about:
  home: https://github.com/ArgonneCPAC/dsps
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Differentiable Stellar Population Synthesis

extra:
  recipe-maintainers:
    - beckermr
