{% set name = "dsps" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 744fd935635c1eafcc08dc91a6145721efc474ad2a35b1faa38c32baf6b06c96

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - jax
    - h5py
{% if version == "0.3.1" %}
    - scipy
{% endif %}
    - diffmah
    - diffstar >=0.1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - dsps

about:
  home: https://github.com/ArgonneCPAC/dsps
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Differentiable Stellar Population Synthesis

extra:
  recipe-maintainers:
    - beckermr
